# Generated by Django 2.1 on 2018-08-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('osver', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('sn', models.CharField(max_length=50)),
                ('cpu_model', models.CharField(max_length=50)),
                ('cpu_num', models.IntegerField()),
                ('memory', models.CharField(max_length=50)),
            ],
        ),
    ]
