# Generated by Django 2.0.7 on 2018-09-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_hostgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='sn',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
